// Generated from crates/secopy-app by `cargo test -p secopy-app`. Don't edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  FROM's Choose…: a folder or files, in one panel (FR-1, FR-2). `None` when cancelled. */
	pickSource: () => typedError<string[] | null, string>(__TAURI_INVOKE("pick_source")),
	/**
	 *  Scans a picked, dropped or chosen drive or source (FR-1..FR-3). A newer scan replaces
	 *  an older one.
	 */
	scanSource: (paths: string[]) => typedError<SessionView, string>(__TAURI_INVOKE("scan_source", { paths })),
	/**  The "Include the folder" checkbox (FR-4); this run's file types stay. */
	setIncludeFolder: (include: boolean) => typedError<SessionView, string>(__TAURI_INVOKE("set_include_folder", { include })),
	/**  Everything the window needs at start; load problems are handed out once. */
	appStart: () => typedError<StartView, string>(__TAURI_INVOKE("app_start")),
	recentDestinations: () => typedError<string[], string>(__TAURI_INVOKE("recent_destinations")),
	selectProfile: (id: string | null) => typedError<SessionView, string>(__TAURI_INVOKE("select_profile", { id })),
	updateProfile: () => typedError<ProfilesView, string>(__TAURI_INVOKE("update_profile")),
	saveProfileAs: (name: string) => typedError<ProfilesView, string>(__TAURI_INVOKE("save_profile_as", { name })),
	createProfile: (input: ProfileInput) => typedError<Profile[], string>(__TAURI_INVOKE("create_profile", { input })),
	editProfile: (id: string, input: ProfileInput) => typedError<ProfilesView, string>(__TAURI_INVOKE("edit_profile", { id, input })),
	deleteProfile: (id: string) => typedError<ProfilesView, string>(__TAURI_INVOKE("delete_profile", { id })),
	setSettings: (settings: Settings) => typedError<Settings, string>(__TAURI_INVOKE("set_settings", { settings })),
	/**  Copy or Copy & Verify, remembered for the next launch (FR-36). */
	setMode: (verify: boolean) => typedError<null, string>(__TAURI_INVOKE("set_mode", { verify })),
	/**  Clears the source; the destination stays ("New copy", RFD §5.4). */
	clearSource: () => typedError<SessionView, string>(__TAURI_INVOKE("clear_source")),
	/**  `None` selects every extension (FR-8, FR-10). */
	setFilter: (selected: (string | null)[] | null) => typedError<SessionView, string>(__TAURI_INVOKE("set_filter", { selected })),
	setDestination: (path: string | null) => typedError<SessionView, string>(__TAURI_INVOKE("set_destination", { path })),
	setConflicts: (policy: ConflictPolicy) => typedError<SessionView, string>(__TAURI_INVOKE("set_conflicts", { policy })),
	sessionView: () => typedError<SessionView, string>(__TAURI_INVOKE("session_view")),
	/**  Starts copying what the main window shows; progress arrives on `on_progress`. */
	startJob: (verify: boolean, onProgress: Channel<ProgressView>) => typedError<null, string>(__TAURI_INVOKE("start_job", { verify, onProgress })),
	pauseJob: () => __TAURI_INVOKE<void>("pause_job"),
	resumeJob: () => __TAURI_INVOKE<void>("resume_job"),
	cancelJob: (removeCopied: boolean) => __TAURI_INVOKE<void>("cancel_job", { removeCopied }),
	jobRunning: () => __TAURI_INVOKE<boolean>("job_running"),
	finishedPage: (offset: number, limit: number, failedOnly: boolean) => typedError<FinishedRow[], string>(__TAURI_INVOKE("finished_page", { offset, limit, failedOnly })),
	jobSummary: () => typedError<{
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: string | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	/**  Items the scan couldn't read, so they weren't copied (#58). */
	unread: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: string | null,
	/**  The checksum file is off in Settings (RFD §5.5). */
	checksumOff: boolean,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there. */
	reportError: string | null,
	/**  A mirror's own figures (plan 7); `None` for a copy. */
	mirror: MirrorSummaryView | null,
	/**  What Cancel's "Also remove the files already copied" did (#54). */
	undone: UndoneView | null,
} | null, string>(__TAURI_INVOKE("job_summary")),
	saveReport: (path: string) => typedError<null, string>(__TAURI_INVOKE("save_report", { path })),
	/**  "Retry failed": only the failed files, checked again (RFD §5.4). */
	retryFailed: () => typedError<SessionView, string>(__TAURI_INVOKE("retry_failed")),
	/**  The UI says which File menu items apply. */
	setMenuState: (setup: boolean, canStart: boolean, copying: boolean) => __TAURI_INVOKE<void>("set_menu_state", { setup, canStart, copying }),
	queue: () => typedError<QueueView, string>(__TAURI_INVOKE("queue")),
	addToQueue: (verify: boolean) => typedError<QueueView, string>(__TAURI_INVOKE("add_to_queue", { verify })),
	removeFromQueue: (index: number) => typedError<QueueView, string>(__TAURI_INVOKE("remove_from_queue", { index })),
	moveInQueue: (from: number, to: number) => typedError<QueueView, string>(__TAURI_INVOKE("move_in_queue", { from, to })),
	clearQueue: () => typedError<QueueView, string>(__TAURI_INVOKE("clear_queue")),
	setQueueOnFailure: (onFailure: OnFailure) => typedError<QueueView, string>(__TAURI_INVOKE("set_queue_on_failure", { onFailure })),
	/**  Starts the queue on its own thread; events arrive on `on_event`. */
	runQueue: (onEvent: Channel<QueueEvent>) => typedError<null, string>(__TAURI_INVOKE("run_queue", { onEvent })),
	queueFinishedPage: (index: number, offset: number, limit: number, failedOnly: boolean) => typedError<FinishedRow[], string>(__TAURI_INVOKE("queue_finished_page", { index, offset, limit, failedOnly })),
	queueSaveReport: (index: number, path: string) => typedError<null, string>(__TAURI_INVOKE("queue_save_report", { index, path })),
	mirrorPresets: () => typedError<MirrorPreset[], string>(__TAURI_INVOKE("mirror_presets")),
	createMirrorPreset: (input: MirrorPresetInput) => typedError<MirrorPreset[], string>(__TAURI_INVOKE("create_mirror_preset", { input })),
	editMirrorPreset: (id: string, input: MirrorPresetInput) => typedError<MirrorPreset[], string>(__TAURI_INVOKE("edit_mirror_preset", { id, input })),
	deleteMirrorPreset: (id: string) => typedError<MirrorPreset[], string>(__TAURI_INVOKE("delete_mirror_preset", { id })),
	/**  A mirror's preview (FR-47); Run mirror then runs it. */
	previewMirror: (id: string, onCompared: Channel<ComparedView>) => typedError<MirrorPreviewView, string>(__TAURI_INVOKE("preview_mirror", { id, onCompared })),
	mirrorPreviewPage: (kind: "new" | "changed" | "removed" | null, offset: number, limit: number) => typedError<PreviewRow[], string>(__TAURI_INVOKE("mirror_preview_page", { kind, offset, limit })),
	/**  Runs the previewed mirror; progress arrives on `on_progress`. */
	runMirror: (id: string, onProgress: Channel<ProgressView>) => typedError<null, string>(__TAURI_INVOKE("run_mirror", { id, onProgress })),
	/**  Stops a preview's deep check. */
	cancelMirrorPreview: () => __TAURI_INVOKE<void>("cancel_mirror_preview"),
	addMirrorToQueue: (id: string) => typedError<QueueView, string>(__TAURI_INVOKE("add_mirror_to_queue", { id })),
};

/* Types */
export type ActiveFileView = {
	id: number,
	name: string,
	path: string,
	verifying: boolean,
	size: number,
	bytesDone: number,
};

/**  How far a preview's deep check is: files compared, of how many (#57). */
export type ComparedView = {
	done: number,
	total: number,
};

/**  What to do with files that exist but differ (FR-17). */
export type ConflictPolicy = "keepBoth" | "overwrite" | "skip";

export type DeletedFiles = {
	mode: DeletedMode,
	/**  Days archived files are kept (archive mode). */
	days: number,
};

/**  What a mirror does with files deleted in the origin (FR-44). */
export type DeletedMode = "archive" | "delete";

export type DestinationView = {
	path: string,
	/**  Where the files will land ("Files will go to", FR-4). */
	copyRoot: string,
	/**  Stops the job (FR-16); Start stays disabled. */
	blocker: string | null,
	freeBytes: number,
	fsKind: string,
	/**
	 *  Items already in the copy root, hidden ones not counted; `None` if it doesn't exist.
	 *  More than zero shows the non-empty warning.
	 */
	existingItems: number | null,
	/**  Files that will fail, first 100 (FR-16). */
	problems: FileProblemView[],
	problemCount: number,
	/**  Same size and date at the destination: skipped, not checked (FR-17). */
	identical: number,
	/**  Different files with the same name (FR-17). */
	differs: number,
	/**  Partial files left by an interrupted copy, to be replaced (FR-18). */
	stalePartials: number,
};

export type ExtensionView = {
	key: string | null,
	/**  ".mov", or "(no extension)". */
	label: string,
	files: number,
	bytes: number,
};

export type FileProblemView = {
	path: string,
	reason: string,
};

/**  One row of the finished list (RFD §5.3). */
export type FinishedRow = {
	id: number,
	path: string,
	/**  Differs from `path` when the copy was kept under a new name. */
	finalPath: string,
	size: number,
	millis: number,
	hash: string | null,
	status: RowStatus,
	/**  Why it failed or was skipped. */
	reason: string | null,
};

export type JobOutcome = "complete" | "failures" | "cancelled" | "stopped";

export type JobPhase = "copying" | "verifying" | 
/**  A mirror archiving or deleting what's gone from its origin (plan 7). */
"removing" | "done";

/**  A saved one-way mirror (plan 7, FR-44). */
export type MirrorPreset = {
	id: string,
	name: string,
	origin: string,
	destination: string,
	deleted: DeletedFiles,
	/**  Also compare contents by checksum (FR-46). */
	deepCheck: boolean,
};

/**  A mirror preset as typed in its editor. */
export type MirrorPresetInput = {
	name: string,
	origin: string,
	destination: string,
	deleted: DeletedFiles,
	deepCheck: boolean,
};

/**  A mirror's preview (FR-47): what a run would do, before anything is touched. */
export type MirrorPreviewView = {
	presetId: string,
	name: string,
	origin: string,
	destination: string,
	newFiles: number,
	newBytes: number,
	changedFiles: number,
	changedBytes: number,
	removedFiles: number,
	/**  Days removed files are archived for; `None` when they are deleted. */
	archiveDays: number | null,
	unchanged: number,
	/**  Why the run looks wrong (FR-50): Run mirror asks first. */
	guard: string | null,
};

/**  What a mirror did besides copying (FR-52). */
export type MirrorSummaryView = {
	/**  Files new in the origin, copied. */
	new: number,
	/**  Files changed in the origin, replaced. */
	updated: number,
	/**  Files gone from the origin, archived or deleted. */
	removed: number,
	/**  Removed files were archived (or deleted). */
	archived: boolean,
	/**  Files that couldn't be archived or deleted, with why. */
	removalFailures: FinishedRow[],
	/**  Why nothing was removed: the copy phase failed or was cancelled. */
	nothingRemoved: string | null,
};

export type OnFailure = "continue" | "stop";

export type PlanView = {
	filesToWrite: number,
	bytesToWrite: number,
	/**  Not enough free space (FR-16). */
	blocker: string | null,
};

export type PreviewKind = "new" | "changed" | "removed";

/**  One file in a mirror's preview. */
export type PreviewRow = {
	path: string,
	size: number,
	kind: PreviewKind,
	reason: string,
};

/**  A saved copy setup for FROM (FR-38): choosing it loads its source and settings. */
export type Profile = {
	/**  Stays the same when the profile is renamed. */
	id: string,
	name: string,
	/**  The directory it loads, as a full path; empty until one is saved into it. */
	source: string,
	/**  "Include the folder" (FR-4). */
	includeFolder: boolean,
	/**  `None` = every file type, including ones never seen. */
	extensions: (string | null)[] | null,
};

/**  A profile as typed in a form (Save as new…, Settings). */
export type ProfileInput = {
	name: string,
	/**  A full path, or empty. */
	source: string,
	includeFolder: boolean,
	extensions: (string | null)[] | null,
};

/**  After a profile change: the profiles and what FROM shows now. */
export type ProfilesView = {
	profiles: Profile[],
	session: SessionView,
};

/**  Sent twice a second while a job runs (RFD §5.3, NFR-5). */
export type ProgressView = {
	phase: JobPhase,
	elapsedMs: number,
	paused: boolean,
	verify: boolean,
	totalFiles: number,
	/**  Bytes the job writes; skipped files are not included. */
	totalBytes: number,
	copiedBytes: number,
	verifiedBytes: number,
	filesDone: number,
	filesSkipped: number,
	filesFailed: number,
	/**  Files of 8 MiB or more in progress. */
	active: ActiveFileView[],
	/**  The job's smaller files, as one steady row; `None` when it has none. */
	smallFiles: SmallFilesView | null,
	/**  Files a mirror is archiving or deleting, while it does (`JobPhase::Removing`). */
	removing: number,
	/**  Whether they are archived (or deleted). */
	archiving: boolean,
	/**  Set once, when the job has stopped for good. */
	fatal: string | null,
};

/**  What a queue run sends to the window. */
export type QueueEvent = 
/**  The job is being checked (its source scanned, the destination looked at). */
{ type: "jobChecking"; index: number; count: number } | 
/**  A queued mirror's deep check: files compared, of how many. */
{ type: "compared"; index: number; done: number; total: number } | 
/**  The checks passed and it runs: a job that can't start never gets this. */
{ type: "jobStarted"; index: number; count: number; job: QueuedJobView } | { type: "progress"; view: ProgressView } | { type: "done"; summary: QueueSummaryView };

/**  How a queued job ended. */
export type QueueResult = "complete" | "failed" | "cancelled" | "notRun";

export type QueueResultView = {
	job: QueuedJobView,
	result: QueueResult,
	/**  Why it failed, was cancelled or didn't run. */
	reason: string | null,
	/**  The job's summary, when it ran. */
	summary: SummaryView | null,
};

export type QueueSummaryView = {
	results: QueueResultView[],
	complete: number,
	count: number,
	millis: number,
	/**  Why the queue couldn't be saved after a job; the run itself went on. */
	saveError: string | null,
};

export type QueueView = {
	jobs: QueuedJobView[],
	onFailure: OnFailure,
	running: boolean,
};

/**  A queued job as the Queue screen shows it (plan 6). */
export type QueuedJobView = {
	/**  "copy", or "unknown" for a job a newer Secopy wrote. */
	kind: string,
	verify: boolean,
	/**  The source as shown ("3 files" for several). */
	source: string,
	destination: string,
	lastError: string | null,
	supported: boolean,
	/**  A mirror's preset name; `None` for a copy. */
	name: string | null,
};

export type RowStatus = "copied" | "verified" | "skipped" | "failed" | 
/**  Stopped by Cancel. */
"cancelled";

/**
 *  Everything the main window shows. Every session command returns the whole view, so the
 *  UI never has to combine partial answers.
 */
export type SessionView = {
	source: SourceView | null,
	/**  Files and bytes the extension filter keeps. */
	selectedFiles: number,
	selectedBytes: number,
	destination: DestinationView | null,
	conflicts: ConflictPolicy,
	plan: PlanView | null,
	/**  The selected source profile's id (FR-38). */
	profileId: string | null,
	/**  This run's choices differ from the profile's: offer Update profile / Save as new…. */
	profileChanged: boolean,
	/**  Why there is no source, e.g. "CARD_A has no PRIVATE/M4ROOT/CLIP". */
	pickProblem: string | null,
	/**  A newer scan replaced this one while it ran (FR-3); the UI keeps its current view. */
	stale: boolean,
};

/**  The Settings screen (RFD §5.5). */
export type Settings = {
	writeChecksumFile: boolean,
	showSystemCount: boolean,
	reportNextToChecksum: boolean,
	/**  A notification when a copy ends while the window isn't in front (3b-2). */
	notifyWhenDone: boolean,
};

export type SmallFilesView = {
	/**  Of the job's small files, those finished (only ever goes up). */
	done: number,
	total: number,
};

export type SourceView = {
	/**  What the user picked: the folder, or "3 files". */
	label: string,
	isFolder: boolean,
	/**  Copy only what's inside the folder (FR-4b) instead of the folder itself. */
	contentsOnly: boolean,
	/**  The picked folder, to scan again when "folder itself / only what's inside" changes. */
	folder: string | null,
	/**
	 *  The failed files of the last job ("Retry failed"): nothing to choose but the
	 *  destination.
	 */
	isRetry: boolean,
	/**  The folder created for "copy the folder itself", e.g. "CLIP". */
	rootDir: string | null,
	files: number,
	bytes: number,
	/**  Sorted by bytes, largest first (FR-8). */
	extensions: ExtensionView[],
	/**  `None` = every extension; otherwise the selected keys (FR-8). */
	selectedExtensions: (string | null)[] | null,
	/**  System files skipped (`.DS_Store`, `Thumbs.db`…); hidden files are copied (FR-12). */
	skippedSystem: number,
	skippedSymlinks: number,
	/**  Things that couldn't be read while scanning, first 20. */
	problems: string[],
	problemCount: number,
};

/**  What the window loads at start (plan 3b-1). */
export type StartView = {
	session: SessionView,
	settings: Settings,
	profiles: Profile[],
	/**  Copy & Verify (true) or Copy, as last used (FR-36). */
	verify: boolean,
	/**  Recent destinations that still exist, most recent first. */
	recentDestinations: string[],
	/**  Saved files that couldn't be read; shown once. */
	warnings: string[],
	/**  The profile last used, when its source is there: the window loads it again (FR-36). */
	lastProfile: string | null,
};

/**  The summary after a job (RFD §5.4). */
export type SummaryView = {
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: string | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	/**  Items the scan couldn't read, so they weren't copied (#58). */
	unread: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: string | null,
	/**  The checksum file is off in Settings (RFD §5.5). */
	checksumOff: boolean,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there. */
	reportError: string | null,
	/**  A mirror's own figures (plan 7); `None` for a copy. */
	mirror: MirrorSummaryView | null,
	/**  What Cancel's "Also remove the files already copied" did (#54). */
	undone: UndoneView | null,
};

/**  The files a cancelled job removed again (#54). */
export type UndoneView = {
	/**  Files it had created, removed. */
	removed: number,
	/**  Files it had replaced, put back from the archive. */
	restored: number,
	/**  Files it had replaced that couldn't be put back: the new version stays. */
	notRestored: number,
	/**  Files that couldn't be removed or put back (the report lists them). */
	failed: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

