// Generated from crates/secopy-app by `cargo test -p secopy-app`. Don't edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  FROM's Choose…: a folder or files, in one panel (FR-1, FR-2). `None` when cancelled. */
	pickSource: () => typedError<string[] | null, string>(__TAURI_INVOKE("pick_source")),
	/**  Scans a picked or dropped source (FR-1..FR-3). A newer scan replaces an older one. */
	scanSource: (paths: string[], contentsOnly: boolean) => typedError<SessionView, string>(__TAURI_INVOKE("scan_source", { paths, contentsOnly })),
	/**  Clears the source; the destination stays ("New copy", RFD §5.4). */
	clearSource: () => typedError<SessionView, string>(__TAURI_INVOKE("clear_source")),
	/**  `None` selects every extension (FR-8, FR-10). */
	setFilter: (selected: (string | null)[] | null) => typedError<SessionView, string>(__TAURI_INVOKE("set_filter", { selected })),
	setDestination: (path: string | null) => typedError<SessionView, string>(__TAURI_INVOKE("set_destination", { path })),
	setConflicts: (policy: ConflictPolicy) => typedError<SessionView, string>(__TAURI_INVOKE("set_conflicts", { policy })),
	sessionView: () => typedError<SessionView, string>(__TAURI_INVOKE("session_view")),
	/**  Starts copying what the main window shows; progress arrives on `on_progress`. */
	startJob: (verify: boolean, onProgress: Channel<ProgressView>) => typedError<null, string>(__TAURI_INVOKE("start_job", { verify, onProgress })),
	pauseJob: () => __TAURI_INVOKE<void>("pause_job"),
	resumeJob: () => __TAURI_INVOKE<void>("resume_job"),
	cancelJob: () => __TAURI_INVOKE<void>("cancel_job"),
	jobRunning: () => __TAURI_INVOKE<boolean>("job_running"),
	finishedPage: (offset: number, limit: number, failedOnly: boolean) => typedError<FinishedRow[], string>(__TAURI_INVOKE("finished_page", { offset, limit, failedOnly })),
	jobSummary: () => typedError<{
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: string | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: string | null,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there. */
	reportError: string | null,
} | null, string>(__TAURI_INVOKE("job_summary")),
	saveReport: (path: string) => typedError<null, string>(__TAURI_INVOKE("save_report", { path })),
	/**  "Retry failed": only the failed files, checked again (RFD §5.4). */
	retryFailed: () => typedError<SessionView, string>(__TAURI_INVOKE("retry_failed")),
};

/* Types */
export type ActiveFileView = {
	id: number,
	name: string,
	path: string,
	verifying: boolean,
	size: number,
	bytesDone: number,
};

/**  What to do with files that exist but differ (FR-17). */
export type ConflictPolicy = "keepBoth" | "overwrite" | "skip";

export type DestinationView = {
	path: string,
	/**  Where the files will land ("Files will go to", FR-4). */
	copyRoot: string,
	/**  Stops the job (FR-16); Start stays disabled. */
	blocker: string | null,
	freeBytes: number,
	fsKind: string,
	/**
	 *  Items already in the copy root, hidden ones not counted; `None` if it doesn't exist.
	 *  More than zero shows the non-empty warning.
	 */
	existingItems: number | null,
	/**  Files that will fail, first 100 (FR-16). */
	problems: FileProblemView[],
	problemCount: number,
	/**  Same size and date at the destination: skipped, not checked (FR-17). */
	identical: number,
	/**  Different files with the same name (FR-17). */
	differs: number,
	/**  Partial files left by an interrupted copy, to be replaced (FR-18). */
	stalePartials: number,
};

export type ExtensionView = {
	key: string | null,
	/**  ".mov", or "(no extension)". */
	label: string,
	files: number,
	bytes: number,
};

export type FileProblemView = {
	path: string,
	reason: string,
};

/**  One row of the finished list (RFD §5.3). */
export type FinishedRow = {
	id: number,
	path: string,
	/**  Differs from `path` when the copy was kept under a new name. */
	finalPath: string,
	size: number,
	millis: number,
	hash: string | null,
	status: RowStatus,
	/**  Why it failed or was skipped. */
	reason: string | null,
};

export type JobOutcome = "complete" | "failures" | "cancelled" | "stopped";

export type JobPhase = "copying" | "verifying" | "done";

export type PlanView = {
	filesToWrite: number,
	bytesToWrite: number,
	/**  Not enough free space (FR-16). */
	blocker: string | null,
};

/**  Sent twice a second while a job runs (RFD §5.3, NFR-5). */
export type ProgressView = {
	phase: JobPhase,
	elapsedMs: number,
	paused: boolean,
	verify: boolean,
	totalFiles: number,
	/**  Bytes the job writes; skipped files are not included. */
	totalBytes: number,
	copiedBytes: number,
	verifiedBytes: number,
	filesDone: number,
	filesSkipped: number,
	filesFailed: number,
	/**  Files of 8 MiB or more in progress. */
	active: ActiveFileView[],
	/**  Smaller files in progress, summed into one row. */
	smallFiles: SmallFilesView | null,
	/**  Set once, when the job has stopped for good. */
	fatal: string | null,
};

export type RowStatus = "copied" | "verified" | "skipped" | "failed";

/**
 *  Everything the main window shows. Every session command returns the whole view, so the
 *  UI never has to combine partial answers.
 */
export type SessionView = {
	source: SourceView | null,
	/**  Files and bytes the extension filter keeps. */
	selectedFiles: number,
	selectedBytes: number,
	destination: DestinationView | null,
	conflicts: ConflictPolicy,
	plan: PlanView | null,
	/**  A newer scan replaced this one while it ran (FR-3); the UI keeps its current view. */
	stale: boolean,
};

export type SmallFilesView = {
	count: number,
	size: number,
	bytesDone: number,
};

export type SourceView = {
	/**  What the user picked: the folder, or "3 files". */
	label: string,
	isFolder: boolean,
	/**  Copy only what's inside the folder (FR-4b) instead of the folder itself. */
	contentsOnly: boolean,
	/**  The picked folder, to scan again when "folder itself / only what's inside" changes. */
	folder: string | null,
	/**
	 *  The failed files of the last job ("Retry failed"): nothing to choose but the
	 *  destination.
	 */
	isRetry: boolean,
	/**  The folder created for "copy the folder itself", e.g. "CLIP". */
	rootDir: string | null,
	files: number,
	bytes: number,
	/**  Sorted by bytes, largest first (FR-8). */
	extensions: ExtensionView[],
	/**  `None` = every extension; otherwise the selected keys (FR-8). */
	selectedExtensions: (string | null)[] | null,
	skippedHidden: number,
	skippedSymlinks: number,
	/**  Things that couldn't be read while scanning, first 20. */
	problems: string[],
	problemCount: number,
};

/**  The summary after a job (RFD §5.4). */
export type SummaryView = {
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: string | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: string | null,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there. */
	reportError: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

