// Generated from crates/secopy-app by `cargo test -p secopy-app`. Don't edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  FROM's Choose…: a folder or files, in one panel (FR-1, FR-2). `None` when cancelled. */
	pickSource: () => typedError<string[] | null, Message>(__TAURI_INVOKE("pick_source")),
	/**
	 *  The window is closing: hides it behind the menu bar icon when that applies (#80); `false`
	 *  and nothing changed otherwise, and the window asks or quits as before.
	 */
	hideToMenuBar: () => __TAURI_INVOKE<boolean>("hide_to_menu_bar"),
	/**  The menu bar panel's content now (#80); it asks when it opens. */
	menubarView: () => __TAURI_INVOKE<{
	heading: Message,
	from: Message | null,
	to: string | null,
	/**  Work done, 0–1; `None` before there is anything to count. */
	fraction: number | null,
	/**  Whole percent done; `None` before there is anything to count ("…"). */
	percent: number | null,
	filesDone: number,
	totalFiles: number,
	/**  Bytes a second; `None` until there is a speed. */
	speed: number | null,
	/**  Milliseconds left; `None` until there is a speed. */
	leftMs: number | null,
	paused: boolean,
	/**  A mirror archiving or deleting, or Cancel putting the destination back. */
	removing: boolean,
	/**  How it ended, once it has. */
	ended: Ended | null,
} | null>("menubar_view"),
	/**  The panel's Open Secopy: the window again, back in the Dock (#80). */
	openMainWindow: () => __TAURI_INVOKE<void>("open_main_window"),
	/**  The panel's Quit Secopy: asks first while a job runs, as ⌘Q does (#80). */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	exportAll: (path: string, what: ExportWhat) => typedError<Message, Message>(__TAURI_INVOKE("export_all", { path, what })),
	/**  What a mirror's archive holds (#101). */
	mirrorArchive: (id: string) => typedError<ArchiveView, Message>(__TAURI_INVOKE("mirror_archive", { id })),
	/**  Deletes a mirror's archive now (#101). */
	deleteMirrorArchive: (id: string) => typedError<ArchiveDeletedView, Message>(__TAURI_INVOKE("delete_mirror_archive", { id })),
	/**  Deletes a mirror's archive at its next run (#101). */
	clearMirrorArchiveNextRun: (id: string) => typedError<MirrorPreset_Serialize[], Message>(__TAURI_INVOKE("clear_mirror_archive_next_run", { id })),
	exportCopyPreset: (id: string, path: string) => typedError<Message, Message>(__TAURI_INVOKE("export_copy_preset", { id, path })),
	exportMirrorPreset: (id: string, path: string) => typedError<Message, Message>(__TAURI_INVOKE("export_mirror_preset", { id, path })),
	/**  Reads a `.secopy` file for the Import screen; changes nothing. */
	openImport: (path: string) => typedError<ImportView, Message>(__TAURI_INVOKE("open_import", { path })),
	applyImport: (choices: ImportChoices) => typedError<ImportDone_Serialize, Message>(__TAURI_INVOKE("apply_import", { choices })),
	/**  A `.secopy` file opened from Finder, once. */
	takeOpenedFile: () => __TAURI_INVOKE<string | null>("take_opened_file"),
	/**
	 *  Scans a picked, dropped or chosen source (FR-1..FR-3). A newer scan replaces
	 *  an older one.
	 */
	scanSource: (paths: string[]) => typedError<SessionView, Message>(__TAURI_INVOKE("scan_source", { paths })),
	/**  The "Include the folder" checkbox (FR-4); this run's file types stay. */
	setIncludeFolder: (include: boolean) => typedError<SessionView, Message>(__TAURI_INVOKE("set_include_folder", { include })),
	/**  Everything the window needs at start; load problems are handed out once. */
	appStart: () => typedError<StartView, Message>(__TAURI_INVOKE("app_start")),
	recentDestinations: () => typedError<string[], Message>(__TAURI_INVOKE("recent_destinations")),
	selectCopyPreset: (id: string | null) => typedError<SessionView, Message>(__TAURI_INVOKE("select_copy_preset", { id })),
	updateCopyPreset: () => typedError<CopyPresetsView, Message>(__TAURI_INVOKE("update_copy_preset")),
	saveCopyPresetAs: (name: string) => typedError<CopyPresetsView, Message>(__TAURI_INVOKE("save_copy_preset_as", { name })),
	createCopyPreset: (input: CopyPresetInput) => typedError<CopyPreset[], Message>(__TAURI_INVOKE("create_copy_preset", { input })),
	editCopyPreset: (id: string, input: CopyPresetInput) => typedError<CopyPresetsView, Message>(__TAURI_INVOKE("edit_copy_preset", { id, input })),
	deleteCopyPreset: (id: string) => typedError<CopyPresetsView, Message>(__TAURI_INVOKE("delete_copy_preset", { id })),
	setSettings: (settings: Settings) => typedError<Settings, Message>(__TAURI_INVOKE("set_settings", { settings })),
	/**  Copy or Copy & Verify, remembered for the next launch (FR-36). */
	setMode: (verify: boolean) => typedError<null, Message>(__TAURI_INVOKE("set_mode", { verify })),
	/**  Clears the source; the destination stays ("New copy", RFD §5.4). */
	clearSource: () => typedError<SessionView, Message>(__TAURI_INVOKE("clear_source")),
	/**  `None` selects every extension (FR-8, FR-10). */
	setFilter: (selected: (string | null)[] | null) => typedError<SessionView, Message>(__TAURI_INVOKE("set_filter", { selected })),
	setDestination: (path: string | null) => typedError<SessionView, Message>(__TAURI_INVOKE("set_destination", { path })),
	setConflicts: (policy: ConflictPolicy) => typedError<SessionView, Message>(__TAURI_INVOKE("set_conflicts", { policy })),
	/**  New copy as it is now (#112). */
	sessionView: () => typedError<SessionView, Message>(__TAURI_INVOKE("session_view")),
	/**  Starts copying what the main window shows; progress arrives on `on_progress`. */
	startJob: (verify: boolean, onProgress: Channel<ProgressView>) => typedError<null, Message>(__TAURI_INVOKE("start_job", { verify, onProgress })),
	pauseJob: () => __TAURI_INVOKE<void>("pause_job"),
	resumeJob: () => __TAURI_INVOKE<void>("resume_job"),
	cancelJob: (removeCopied: boolean) => __TAURI_INVOKE<void>("cancel_job", { removeCopied }),
	jobRunning: () => __TAURI_INVOKE<boolean>("job_running"),
	finishedPage: (offset: number, limit: number, failedOnly: boolean) => typedError<FinishedRow[], Message>(__TAURI_INVOKE("finished_page", { offset, limit, failedOnly })),
	jobSummary: () => typedError<{
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: Message | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	/**  Items the scan couldn't read, so they weren't copied (#58). */
	unread: number,
	/**  The destination reported an error while the copy was made durable (#58). */
	durabilityError: Message | null,
	/**  Empty directories that couldn't be created (#58); listed with the failures. */
	dirErrors: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: Message | null,
	/**  The checksum file is off in Settings (RFD §5.5). */
	checksumOff: boolean,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there (each place it was written). */
	reportErrors: Message[],
	/**  A mirror's own figures (plan 7); `None` for a copy. */
	mirror: MirrorSummaryView_Serialize | null,
	/**  What Cancel's "Also remove the files already copied" did (#54). */
	undone: UndoneView | null,
	/**  A check's own figures (plan 8); `None` for a copy or a mirror. */
	check: CheckSummaryView | null,
} | null, Message>(__TAURI_INVOKE("job_summary")),
	saveReport: (path: string) => typedError<null, Message>(__TAURI_INVOKE("save_report", { path })),
	/**  "Retry": only the failed files, checked again (RFD §5.4). */
	retryFailed: () => typedError<SessionView, Message>(__TAURI_INVOKE("retry_failed")),
	/**  The UI says which File menu items apply. */
	setMenuState: (setup: boolean, canStart: boolean, copying: boolean, busy: boolean) => __TAURI_INVOKE<void>("set_menu_state", { setup, canStart, copying, busy }),
	queue: () => typedError<QueueView, Message>(__TAURI_INVOKE("queue")),
	addToQueue: (verify: boolean) => typedError<QueueView, Message>(__TAURI_INVOKE("add_to_queue", { verify })),
	removeFromQueue: (index: number) => typedError<QueueView, Message>(__TAURI_INVOKE("remove_from_queue", { index })),
	moveInQueue: (from: number, to: number) => typedError<QueueView, Message>(__TAURI_INVOKE("move_in_queue", { from, to })),
	clearQueue: () => typedError<QueueView, Message>(__TAURI_INVOKE("clear_queue")),
	setQueueOnFailure: (onFailure: OnFailure) => typedError<QueueView, Message>(__TAURI_INVOKE("set_queue_on_failure", { onFailure })),
	/**  Starts the queue on its own thread; events arrive on `on_event`. */
	runQueue: (onEvent: Channel<QueueEvent_Deserialize>) => typedError<null, Message>(__TAURI_INVOKE("run_queue", { onEvent })),
	queueFinishedPage: (index: number, offset: number, limit: number, failedOnly: boolean) => typedError<FinishedRow[], Message>(__TAURI_INVOKE("queue_finished_page", { index, offset, limit, failedOnly })),
	queueSaveReport: (index: number, path: string) => typedError<null, Message>(__TAURI_INVOKE("queue_save_report", { index, path })),
	mirrorPresets: () => typedError<MirrorPreset_Serialize[], Message>(__TAURI_INVOKE("mirror_presets")),
	createMirrorPreset: (input: MirrorPresetInput) => typedError<MirrorPreset_Serialize[], Message>(__TAURI_INVOKE("create_mirror_preset", { input })),
	editMirrorPreset: (id: string, input: MirrorPresetInput) => typedError<MirrorPreset_Serialize[], Message>(__TAURI_INVOKE("edit_mirror_preset", { id, input })),
	deleteMirrorPreset: (id: string) => typedError<MirrorPreset_Serialize[], Message>(__TAURI_INVOKE("delete_mirror_preset", { id })),
	/**  A mirror's preview (FR-47); the preview's Start then runs it. */
	previewMirror: (id: string, onCompared: Channel<ComparedView>) => typedError<MirrorPreviewView, Message>(__TAURI_INVOKE("preview_mirror", { id, onCompared })),
	mirrorPreviewPage: (kind: "new" | "changed" | "removed" | null, offset: number, limit: number) => typedError<PreviewRow[], Message>(__TAURI_INVOKE("mirror_preview_page", { kind, offset, limit })),
	/**  Runs the previewed mirror; progress arrives on `on_progress`. */
	runMirror: (id: string, onProgress: Channel<ProgressView>) => typedError<null, Message>(__TAURI_INVOKE("run_mirror", { id, onProgress })),
	/**  Stops a preview's deep check. */
	cancelMirrorPreview: () => __TAURI_INVOKE<void>("cancel_mirror_preview"),
	addMirrorToQueue: (id: string) => typedError<QueueView, Message>(__TAURI_INVOKE("add_mirror_to_queue", { id })),
	/**  Verify's Choose…: what `path`'s checksum files list (plan 8). */
	checkDirectory: (path: string) => typedError<CheckView, Message>(__TAURI_INVOKE("check_directory", { path })),
	/**  Verify's Start: checks the directory chosen last; progress arrives on `on_progress`. */
	startCheck: (path: string, onProgress: Channel<ProgressView>) => typedError<null, Message>(__TAURI_INVOKE("start_check", { path, onProgress })),
	addCheckToQueue: (path: string) => typedError<QueueView, Message>(__TAURI_INVOKE("add_check_to_queue", { path })),
};

/* Types */
export type ActiveFileView = {
	id: number,
	name: string,
	path: string,
	verifying: boolean,
	size: number,
	bytesDone: number,
};

/**  What "Delete them now" did (#101). */
export type ArchiveDeletedView = {
	removed: number,
	/**  Archived files that couldn't be deleted, and when they go instead. */
	notDeleted: Message | null,
};

/**
 *  What a mirror's archive holds (#99, #101): shown on the mirror's screen, and asked before
 *  switching it to Delete.
 */
export type ArchiveView = {
	files: number,
	bytes: number,
	/**  When its oldest run was archived (RFC 3339). */
	oldest: string | null,
	/**  The destination is there: when not, nothing is known about its archive. */
	connected: boolean,
	/**  A job or the queue runs: the archive isn't deleted now. */
	busy: boolean,
};

/**
 *  A placeholder's value. The UI formats numbers for its language, a `Size` as bytes
 *  ("212.4 GB"), translates a nested `Message` first and joins a `List` ("a, b").
 */
export type Arg = 
/**  Counts and bytes are exact as `f64` up to 2^53. */
number | string | Message[] | { bytes: number } | Message;

/**  What a check found (plan 8). */
export type CheckSummaryView = {
	intact: number,
	changed: number,
	missing: number,
	/**  Couldn't be read. */
	failed: number,
	/**  Files no checksum file lists. */
	notChecked: number,
	checksumFiles: number,
	/**  Problems in the checksum files: "file:line: why", the first 1,000. */
	problems: Message[],
	/**  Problems past the ones listed; `None` when every one is (#69). */
	moreProblems?: number | null,
};

/**  A directory about to be checked (plan 8): what its checksum files list. */
export type CheckView = {
	directory: string,
	checksumFiles: number,
	/**  Files the checksum files list. */
	files: number,
	bytes: number,
	notChecked: number,
	/**  Problems in the checksum files: "file:line: why". */
	problems: Message[],
};

/**  How far a preview's deep check is: files compared, of how many (#57). */
export type ComparedView = {
	done: number,
	total: number,
};

/**  What to do with files that exist but differ (FR-17). */
export type ConflictPolicy = "keepBoth" | "overwrite" | "skip";

/**  A saved copy setup for FROM (FR-38): choosing it loads its source and settings. */
export type CopyPreset = {
	/**  Stays the same when the preset is renamed. */
	id: string,
	name: string,
	/**  The directory it loads, as a full path; empty until one is saved into it. */
	source: string,
	/**  "Include the folder" (FR-4). */
	includeFolder: boolean,
	/**  `None` = every file type, including ones never seen. */
	extensions: (string | null)[] | null,
};

/**  A copy preset as typed in a form (Save as…, the Copy presets screen). */
export type CopyPresetInput = {
	name: string,
	/**  A full path, or empty. */
	source: string,
	includeFolder: boolean,
	extensions: (string | null)[] | null,
};

/**  After a copy preset change: the presets and what FROM shows now. */
export type CopyPresetsView = {
	presets: CopyPreset[],
	session: SessionView,
};

export type DeletedFiles = {
	mode: DeletedMode,
	/**  Days archived files are kept (archive mode). */
	days: number,
};

/**  What a mirror does with files deleted in the origin (FR-44). */
export type DeletedMode = "archive" | "delete";

export type DestinationView = {
	path: string,
	/**  Where the files will land ("Files will go to", FR-4). */
	copyRoot: string,
	/**  Stops the job (FR-16); Start stays disabled. */
	blocker: Message | null,
	/**  Available, counting purgeable space, as Finder shows it (#108). */
	freeBytes: number,
	/**
	 *  The destination's file system as a code: `apfs`, `hfs`, `exfat`, `fat32`, `ntfs`,
	 *  `smb`, `nfs`, or `other` (then `fs_name` says which).
	 */
	fsKind: string,
	fsName: string | null,
	/**
	 *  Items already in the copy root, hidden ones not counted; `None` if it doesn't exist.
	 *  More than zero shows the non-empty warning.
	 */
	existingItems: number | null,
	/**  Files that will fail, first 100 (FR-16). */
	problems: FileProblemView[],
	problemCount: number,
	/**  Same size and date at the destination: skipped, not checked (FR-17). */
	identical: number,
	/**  Different files with the same name (FR-17). */
	differs: number,
	/**  Partial files left by an interrupted copy, to be replaced (FR-18). */
	stalePartials: number,
};

export type Ended = {
	/**  Complete: every file done. Anything else is not. */
	ok: boolean,
	text: Message,
};

/**  What goes in an export (#77). */
export type ExportWhat = {
	settings: boolean,
	copyPresets: boolean,
	mirrorPresets: boolean,
};

export type ExtensionView = {
	key: string | null,
	files: number,
	bytes: number,
};

export type FileProblemView = {
	path: string,
	reason: Message,
};

/**  One row of the finished list (RFD §5.3). */
export type FinishedRow = {
	id: number,
	path: string,
	/**  Differs from `path` when the copy was kept under a new name. */
	finalPath: string,
	size: number,
	millis: number,
	hash: string | null,
	status: RowStatus,
	/**  Why it failed or was skipped. */
	reason: Message | null,
};

/**  What the user ticked: presets by their index in the file. */
export type ImportChoices = {
	settings: boolean,
	copyPresets: PresetChoice[],
	mirrorPresets: PresetChoice[],
};

/**  After Import: what to say, and everything the window shows, as saved (#77). */
export type ImportDone = ImportDone_Serialize | ImportDone_Deserialize;

/**  After Import: what to say, and everything the window shows, as saved (#77). */
export type ImportDone_Deserialize = {
	message: Message,
	/**  Part of it couldn't be saved; `message` says what. */
	failed: boolean,
	settings: Settings,
	copyPresets: CopyPreset[],
	mirrorPresets: MirrorPreset_Deserialize[],
};

/**  After Import: what to say, and everything the window shows, as saved (#77). */
export type ImportDone_Serialize = {
	message: Message,
	/**  Part of it couldn't be saved; `message` says what. */
	failed: boolean,
	settings: Settings,
	copyPresets: CopyPreset[],
	mirrorPresets: MirrorPreset_Serialize[],
};

/**  What the Import screen shows: nothing is changed by making it. */
export type ImportView = {
	fileName: string,
	/**  `None`: the file has no settings. */
	settings: SettingsImport | null,
	copyPresets: PresetImport[],
	mirrorPresets: PresetImport[],
};

export type JobOutcome = "complete" | "failures" | "cancelled" | "stopped";

export type JobPhase = "copying" | "verifying" | 
/**  A mirror archiving or deleting what's gone from its origin (plan 7). */
"removing" | "done";

/**
 *  A text for the UI: a catalog key and the values of its placeholders. Build it with
 *  [`msg!`](crate::msg).
 */
export type Message = {
	key: string,
	args: { [key in string]: Arg },
};

/**  A saved one-way mirror (plan 7, FR-44). */
export type MirrorPreset = MirrorPreset_Serialize | MirrorPreset_Deserialize;

/**  A mirror preset as typed in its editor. */
export type MirrorPresetInput = {
	name: string,
	origin: string,
	destination: string,
	deleted: DeletedFiles,
	deepCheck: boolean,
};

/**  A saved one-way mirror (plan 7, FR-44). */
export type MirrorPreset_Deserialize = {
	id: string,
	name: string,
	origin: string,
	destination: string,
	deleted: DeletedFiles,
	/**  Also compare contents by checksum (FR-46). */
	deepCheck: boolean,
	/**
	 *  "Delete it at the next run" (#101): the destination whose archive the next run deletes
	 *  first. Kept with its path, so a later change of destination never points it elsewhere.
	 */
	clearArchive?: string | null,
};

/**  A saved one-way mirror (plan 7, FR-44). */
export type MirrorPreset_Serialize = {
	id: string,
	name: string,
	origin: string,
	destination: string,
	deleted: DeletedFiles,
	/**  Also compare contents by checksum (FR-46). */
	deepCheck: boolean,
	/**
	 *  "Delete it at the next run" (#101): the destination whose archive the next run deletes
	 *  first. Kept with its path, so a later change of destination never points it elsewhere.
	 */
	clearArchive?: string | null,
};

/**  A mirror's preview (FR-47): what a run would do, before anything is touched. */
export type MirrorPreviewView = {
	presetId: string,
	name: string,
	origin: string,
	destination: string,
	newFiles: number,
	newBytes: number,
	changedFiles: number,
	changedBytes: number,
	removedFiles: number,
	/**  Days removed files are archived for; `None` when they are deleted. */
	archiveDays: number | null,
	/**  Files that will fail (a name the destination can't take, something in the way). */
	failing: number,
	unchanged: number,
	/**  Why the run looks wrong (FR-50): the preview's Start asks first. */
	guard: Message | null,
};

/**  What a mirror did besides copying (FR-52). */
export type MirrorSummaryView = MirrorSummaryView_Serialize | MirrorSummaryView_Deserialize;

/**  What a mirror did besides copying (FR-52). */
export type MirrorSummaryView_Deserialize = {
	/**  Files new in the origin, copied. */
	new: number,
	/**  Files changed in the origin, replaced. */
	updated: number,
	/**  Files gone from the origin, archived or deleted. */
	removed: number,
	/**  Removed files were archived (or deleted). */
	archived: boolean,
	/**  Files that couldn't be archived or deleted, with why. */
	removalFailures: FinishedRow[],
	/**  Why nothing was removed: the copy phase failed or was cancelled. */
	nothingRemoved: Message | null,
	/**  Archived files the user asked to delete that couldn't be (#101), and when they go. */
	archiveNotDeleted?: Message | null,
};

/**  What a mirror did besides copying (FR-52). */
export type MirrorSummaryView_Serialize = {
	/**  Files new in the origin, copied. */
	new: number,
	/**  Files changed in the origin, replaced. */
	updated: number,
	/**  Files gone from the origin, archived or deleted. */
	removed: number,
	/**  Removed files were archived (or deleted). */
	archived: boolean,
	/**  Files that couldn't be archived or deleted, with why. */
	removalFailures: FinishedRow[],
	/**  Why nothing was removed: the copy phase failed or was cancelled. */
	nothingRemoved: Message | null,
	/**  Archived files the user asked to delete that couldn't be (#101), and when they go. */
	archiveNotDeleted?: Message | null,
};

export type OnFailure = "continue" | "stop";

/**  What the panel under the icon shows: figures and messages, in the UI's words. */
export type PanelView = {
	heading: Message,
	from: Message | null,
	to: string | null,
	/**  Work done, 0–1; `None` before there is anything to count. */
	fraction: number | null,
	/**  Whole percent done; `None` before there is anything to count ("…"). */
	percent: number | null,
	filesDone: number,
	totalFiles: number,
	/**  Bytes a second; `None` until there is a speed. */
	speed: number | null,
	/**  Milliseconds left; `None` until there is a speed. */
	leftMs: number | null,
	paused: boolean,
	/**  A mirror archiving or deleting, or Cancel putting the destination back. */
	removing: boolean,
	/**  How it ended, once it has. */
	ended: Ended | null,
};

export type PlanView = {
	filesToWrite: number,
	bytesToWrite: number,
	/**  Not enough space (FR-16). */
	blocker: Message | null,
	/**  It fits only once macOS frees purgeable space: a warning, not a block (#108). */
	purgeable: Message | null,
};

export type PresetChoice = {
	index: number,
	/**  Replace your preset with the same name; otherwise Keep both. */
	replace: boolean,
};

export type PresetImport = {
	/**  Empty when the preset in the file has none. */
	name: string,
	/**  A copy preset's source, or a mirror's origin and destination. */
	paths: string[],
	/**  The name of your preset it has, in any letter case. */
	clash: string | null,
	/**  The name Keep both gives it (its own when nothing clashes). */
	newName: string,
	/**  Paths that aren't on this Mac now: a note, not an error. */
	missing: string[],
	/**  Why it can't be imported. */
	problem: Message | null,
	/**  It stands for the file's whole list of presets, which can't be read. */
	section: boolean,
};

export type PreviewKind = "new" | "changed" | "removed";

/**  One file in a mirror's preview. */
export type PreviewRow = {
	path: string,
	size: number,
	kind: PreviewKind,
	reason: Message,
};

/**  Sent twice a second while a job runs (RFD §5.3, NFR-5). */
export type ProgressView = {
	phase: JobPhase,
	elapsedMs: number,
	paused: boolean,
	verify: boolean,
	totalFiles: number,
	/**  Bytes the job writes; skipped files are not included. */
	totalBytes: number,
	copiedBytes: number,
	verifiedBytes: number,
	filesDone: number,
	filesSkipped: number,
	filesFailed: number,
	/**  Files of 8 MiB or more in progress. */
	active: ActiveFileView[],
	/**  The job's smaller files, as one steady row; `None` when it has none. */
	smallFiles: SmallFilesView | null,
	/**  Files a mirror is archiving or deleting, while it does (`JobPhase::Removing`). */
	removing: number,
	/**  Whether they are archived (or deleted). */
	archiving: boolean,
	/**
	 *  A cancelled job removing the files it copied (Cancel's "Also remove…"), while it does
	 *  (`JobPhase::Removing`).
	 */
	undoing: boolean,
	/**  Set once, when the job has stopped for good. */
	fatal: Message | null,
};

/**  What a queue run sends to the window. */
export type QueueEvent = QueueEvent_Serialize | QueueEvent_Deserialize;

/**  What a queue run sends to the window. */
export type QueueEvent_Deserialize = 
/**  The job is being checked (its source scanned, the destination looked at). */
({ type: "jobChecking"; index: number; count: number }) & { done?: never; job?: never; summary?: never; total?: never; view?: never } | 
/**  A queued mirror's deep check: files compared, of how many. */
({ type: "compared"; index: number; done: number; total: number }) & { count?: never; job?: never; summary?: never; view?: never } | 
/**  The checks passed and it runs: a job that can't start never gets this. */
({ type: "jobStarted"; index: number; count: number; job: QueuedJobView }) & { done?: never; summary?: never; total?: never; view?: never } | ({ type: "progress"; view: ProgressView }) & { count?: never; done?: never; index?: never; job?: never; summary?: never; total?: never } | ({ type: "done"; summary: QueueSummaryView_Deserialize }) & { count?: never; done?: never; index?: never; job?: never; total?: never; view?: never };

/**  What a queue run sends to the window. */
export type QueueEvent_Serialize = 
/**  The job is being checked (its source scanned, the destination looked at). */
({ type: "jobChecking"; index: number; count: number }) & { done?: never; job?: never; summary?: never; total?: never; view?: never } | 
/**  A queued mirror's deep check: files compared, of how many. */
({ type: "compared"; index: number; done: number; total: number }) & { count?: never; job?: never; summary?: never; view?: never } | 
/**  The checks passed and it runs: a job that can't start never gets this. */
({ type: "jobStarted"; index: number; count: number; job: QueuedJobView }) & { done?: never; summary?: never; total?: never; view?: never } | ({ type: "progress"; view: ProgressView }) & { count?: never; done?: never; index?: never; job?: never; summary?: never; total?: never } | ({ type: "done"; summary: QueueSummaryView_Serialize }) & { count?: never; done?: never; index?: never; job?: never; total?: never; view?: never };

/**  How a queued job ended. */
export type QueueResult = "complete" | "failed" | "cancelled" | "notRun";

export type QueueResultView = QueueResultView_Serialize | QueueResultView_Deserialize;

export type QueueResultView_Deserialize = {
	job: QueuedJobView,
	result: QueueResult,
	/**  Why it failed, was cancelled or didn't run. */
	reason: Message | null,
	/**  The job's summary, when it ran. */
	summary: SummaryView_Deserialize | null,
};

export type QueueResultView_Serialize = {
	job: QueuedJobView,
	result: QueueResult,
	/**  Why it failed, was cancelled or didn't run. */
	reason: Message | null,
	/**  The job's summary, when it ran. */
	summary: SummaryView_Serialize | null,
};

export type QueueSummaryView = QueueSummaryView_Serialize | QueueSummaryView_Deserialize;

export type QueueSummaryView_Deserialize = {
	results: QueueResultView_Deserialize[],
	complete: number,
	count: number,
	millis: number,
	/**  Why the queue couldn't be saved after a job; the run itself went on. */
	saveError: Message | null,
};

export type QueueSummaryView_Serialize = {
	results: QueueResultView_Serialize[],
	complete: number,
	count: number,
	millis: number,
	/**  Why the queue couldn't be saved after a job; the run itself went on. */
	saveError: Message | null,
};

export type QueueView = {
	jobs: QueuedJobView[],
	onFailure: OnFailure,
};

/**  A queued job as the Queue screen shows it (plan 6). */
export type QueuedJobView = {
	/**  "copy", "mirror", or "unknown" for a job a newer Secopy wrote. */
	kind: string,
	verify: boolean,
	/**  The source as shown ("3 files" for several). */
	source: Message,
	destination: string,
	lastError: Message | null,
	supported: boolean,
	/**  A mirror's preset name; `None` for a copy. */
	name: string | null,
};

export type RowStatus = "copied" | "verified" | "skipped" | "failed" | 
/**  Stopped by Cancel. */
"cancelled" | 
/**  A check read it as it was copied (plan 8). */
"intact" | 
/**  A check read something else than was copied. */
"changed" | 
/**  A check didn't find it. */
"missing";

/**
 *  Everything the main window shows. Every session command returns the whole view, so the
 *  UI never has to combine partial answers.
 */
export type SessionView = {
	source: SourceView | null,
	/**  Files and bytes the extension filter keeps. */
	selectedFiles: number,
	selectedBytes: number,
	destination: DestinationView | null,
	conflicts: ConflictPolicy,
	plan: PlanView | null,
	/**  The selected copy preset's id (FR-38). */
	presetId: string | null,
	/**  This run's choices differ from the preset's: offer Update / Save as…. */
	presetChanged: boolean,
	/**  Why there is no source, e.g. "CARD_A isn't connected." */
	pickProblem: Message | null,
	/**  A newer scan replaced this one while it ran (FR-3); the UI keeps its current view. */
	stale: boolean,
};

/**  The Settings screen (RFD §5.5). */
export type Settings = {
	writeChecksumFile: boolean,
	showSystemCount: boolean,
	reportNextToChecksum: boolean,
	/**  A notification when a copy ends while the window isn't in front (3b-2). */
	notifyWhenDone: boolean,
	/**  Closing the window during a job hides it, with a menu bar icon (#80). */
	keepInMenuBar: boolean,
};

export type SettingsImport = {
	/**  "Write the checksum file: on → off"; empty when they're the same as yours. */
	changes: Message[],
	problem: Message | null,
};

export type SmallFilesView = {
	/**  Of the job's small files, those finished (only ever goes up). */
	done: number,
	total: number,
};

export type SourceView = {
	/**  What the user picked: the directory, or "3 files". */
	label: Message,
	isFolder: boolean,
	/**  Copy only what's inside the folder (FR-4b) instead of the folder itself. */
	contentsOnly: boolean,
	/**  The picked folder, to scan again when "folder itself / only what's inside" changes. */
	folder: string | null,
	/**
	 *  The failed files of the last job ("Retry"): nothing to choose but the
	 *  destination.
	 */
	isRetry: boolean,
	/**  The folder created for "copy the folder itself", e.g. "CLIP". */
	rootDir: string | null,
	files: number,
	bytes: number,
	/**  Sorted by bytes, largest first (FR-8). */
	extensions: ExtensionView[],
	/**  `None` = every extension; otherwise the selected keys (FR-8). */
	selectedExtensions: (string | null)[] | null,
	/**  System files skipped (`.DS_Store`, `Thumbs.db`…); hidden files are copied (FR-12). */
	skippedSystem: number,
	skippedSymlinks: number,
	/**  Things that couldn't be read while scanning, first 20. */
	problems: Message[],
	problemCount: number,
};

/**  What the window loads at start (plan 3b-1). */
export type StartView = {
	session: SessionView,
	settings: Settings,
	copyPresets: CopyPreset[],
	/**  Copy & Verify (true) or Copy, as last used (FR-36). */
	verify: boolean,
	/**  Recent destinations that still exist, most recent first. */
	recentDestinations: string[],
	/**  Saved files that couldn't be read; shown once. */
	warnings: Message[],
	/**  The copy preset last used, when its source is there: the window loads it again (FR-36). */
	lastPreset: string | null,
};

/**  The summary after a job (RFD §5.4). */
export type SummaryView = SummaryView_Serialize | SummaryView_Deserialize;

/**  The summary after a job (RFD §5.4). */
export type SummaryView_Deserialize = {
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: Message | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	/**  Items the scan couldn't read, so they weren't copied (#58). */
	unread: number,
	/**  The destination reported an error while the copy was made durable (#58). */
	durabilityError: Message | null,
	/**  Empty directories that couldn't be created (#58); listed with the failures. */
	dirErrors: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: Message | null,
	/**  The checksum file is off in Settings (RFD §5.5). */
	checksumOff: boolean,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there (each place it was written). */
	reportErrors: Message[],
	/**  A mirror's own figures (plan 7); `None` for a copy. */
	mirror: MirrorSummaryView_Deserialize | null,
	/**  What Cancel's "Also remove the files already copied" did (#54). */
	undone: UndoneView | null,
	/**  A check's own figures (plan 8); `None` for a copy or a mirror. */
	check: CheckSummaryView | null,
};

/**  The summary after a job (RFD §5.4). */
export type SummaryView_Serialize = {
	outcome: JobOutcome,
	/**  Why the job stopped, for `JobOutcome::Stopped`. */
	stoppedBecause: Message | null,
	verify: boolean,
	files: number,
	copied: number,
	verified: number,
	skippedIdentical: number,
	skippedDifferent: number,
	failed: number,
	/**  Items the scan couldn't read, so they weren't copied (#58). */
	unread: number,
	/**  The destination reported an error while the copy was made durable (#58). */
	durabilityError: Message | null,
	/**  Empty directories that couldn't be created (#58); listed with the failures. */
	dirErrors: number,
	notStarted: number,
	bytesWritten: number,
	millis: number,
	/**  Failed files with their reasons, first 1,000. */
	failures: FinishedRow[],
	/**  Rows in the finished list: every file the job got to. */
	finished: number,
	copyRoot: string,
	checksumFile: string | null,
	checksumError: Message | null,
	/**  The checksum file is off in Settings (RFD §5.5). */
	checksumOff: boolean,
	/**  The text report saved in the app's data folder (FR-35). */
	reportFile: string | null,
	/**  Why the report couldn't be saved there (each place it was written). */
	reportErrors: Message[],
	/**  A mirror's own figures (plan 7); `None` for a copy. */
	mirror: MirrorSummaryView_Serialize | null,
	/**  What Cancel's "Also remove the files already copied" did (#54). */
	undone: UndoneView | null,
	/**  A check's own figures (plan 8); `None` for a copy or a mirror. */
	check: CheckSummaryView | null,
};

/**  The files a cancelled job removed again (#54). */
export type UndoneView = {
	/**  Files it had created, removed. */
	removed: number,
	/**  Files it had replaced that couldn't be put back: the new version stays. */
	notRestored: number,
	/**  Files that couldn't be removed or put back (the report lists them). */
	failed: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

